spring:
  datasource:
    username: root
    password: Chamara@7788
    url: jdbc:mysql://localhost:3306/orderservice
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    spring.jpa.show-sql: true
    spring.jpa.hibernate:
      ddl-auto: create-update
    spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    server.port: 8080
    generate-ddl: true
    open-in-view: true